export const pages = [
    "Home",
    "Asteroids NeoWs",
    "DONKI",
    "Earth",
    "EONET",
    "EPIC",
    "Exoplanet",
    "GeneLab",
    "InSight",
    "Mars Rover Photos",
    "NASA Image and Video Library",
    "TechTransfer",
    "Satellite Situation Center",
    "SSD/CNEOS",
    "Techport",
    "TLE API",
    "Vesta/Moon/Mars Trek WMTS",
];
